### PR TITLE
Typo fix Mapper{Read,Write}PPU in writeCartridgePPU

### PR DESCRIPTION
**Pull request by OPNA2608**
Since 9039fa0ccfe7bc2437a0bea52d66cfd2be601329, the build is broken (on Linux?, aside from #1):

```
[ 40%] Building C object NES Emulator/CMakeFiles/nesemu.dir/cartridge.c.o
/build/NESEmulator/NES Emulator/cartridge.c: In function 'writeCartridgePPU':
/build/NESEmulator/NES Emulator/cartridge.c:53:44: error: macro "MapperReadPPU" passed 3 arguments, but takes just 2
   53 |  MapperReadPPU(cartridge->mapper, addr, val);
      |                                            ^
In file included from /build/NESEmulator/NES Emulator/cartridge.c:6:
/build/NESEmulator/NES Emulator/mapper.h:23: note: macro "MapperReadPPU" defined here
   23 | #define MapperReadPPU(mapper, addr) mapper->read_ppu(mapper->mapperStruct, addr)
      |
/build/NESEmulator/NES Emulator/cartridge.c:53:2: error: 'MapperReadPPU' undeclared (first use in this function)
   53 |  MapperReadPPU(cartridge->mapper, addr, val);
      |  ^~~~~~~~~~~~~
/build/NESEmulator/NES Emulator/cartridge.c:53:2: note: each undeclared identifier is reported only once for each function it appears in
```

Prolly a copy-pasting error.

### CODE REVIEW

**Comment by Lauchmelder23** [comment]
> Since [9039fa0](https://github.com/Lauchmelder23/NESEmulator/commit/9039fa0ccfe7bc2437a0bea52d66cfd2be601329), the build is broken (on Linux?, aside from #1):

It is very certain that this project never built on Linux in the first place, I never stopped to verify if the project is cross-platform.
